### ISSUE TITLE
problems running pantagruel commands

### ISSUE THREAD

**Issue by ElitaJaun** [flass/pantagruel#1]
Hi, 

I have installed pantagruel and all dependencies as per instructions (which are very easy to follow - thanks :)) 

however, when I try to run to test if commands working, for e.g. 
_pantagruel -h_

I get:
_pantagruel: command not found_ 

during installation I did not get any errors, just this message:
_The version of InterProScan you are using is 5.32-71.0
The version of the lookup service you are using is 5.33-72.0
As the data in these versions is not the same, you cannot use this match lookup service.
InterProScan will now run locally_

would this have anything to do with the command not found?

**Comment by flass** [comment]
Hi Elita,

thanks very much for the feedback!

Ok these are two separate issues:

1) About the InterProScan error: 
the version of InterProScan to download was hard-coded and did not match the last version; I added a line to look it up so the downloaded version will be the last - so you'll have to re-run the install script.
Please note that InterProscan is regularly updated, and the [install_dependencies.sh](https://github.com/flass/pantagruel/blob/master/install_dependencies.sh) script would need to be run again prior to executing the task 'functional', in order to make sure that the program is up to date and most importantly in sync with the look-up service (without which functional annotation would take ages). I added a check in the task script.
This was fixed in commits 66cd507, cba00f2, 89c89c5 and b4a383d.

2) about the not finding the `pantagruel` command:
I relied on linking the executable to a `$HOME/bin/` folder, which is created and added to the PATH environment variable definition in your `$HOME/.bashrc` file at the end of the install procedure (see [script](https://github.com/flass/pantagruel/blob/master/install_dependencies.sh)). This .bashrc file then needs to be loaded to make these changes effective: you can either run `source $HOME/.bashrc` or just open a new interactive session. I clarified that in the [INSTALL](https://github.com/flass/pantagruel/blob/master/INSTALL.md) page. Note this would not be effective in a non-interactive bash session.
I chose to add the script tot this user-specific folder to avoid conflicts of reference in PATH for different users sharing the same machine.
This was fixed in commit 66cd507.

Please let me know if that works for you now.

Best wishes,
Florent

**Comment by ElitaJaun** [comment]
Thank you Florent.
