### ISSUE TITLE
Updating the software when working on a server without administrator rights

### ISSUE THREAD

**Issue by megaptera-helvetiae** [flass/pantagruel#26]
Hi Florent,
I asked our admins to install Pantagruel, hence, I do not have administrator rights myself. 

While Pantagruel is under development, how often should I ask them to update it? (They get pretty annoyed every time I ask.) Are you announcing bigger changes/releases somewhere?

How does "panup" work?
Is this a workaround so that I could update it as a user?
Do the admins have to install this module for me and then I can run the following command to update:

panup
pantagruel -i previous_config_file --refresh init

Thanks for answering these general questions.

Laetitia

**Comment by flass** [comment]
Hi Laetitia,

- to the question "how often should I update Pantagruel?", the answer is: quite often as I regularly make fixes and improvements.
- to the question "how often should I ask [my system admins] to update [Pantagruel]?", the answer is: not often at all.
The admin rights are only required for the initial installation of pantagruel, i.e. running the script `install_dependencies.sh` where all the Debian, R, python, etc. packages on which Pantagruel depend are installed.
My updates of the code are made on pantagruel scripts, which you can easily update using a `git pull` command on your repository. Because they're scripts, they need no compiling or installation, so no admin rights. 

In rare occasions of deep changes to the pipeline, I would add a dependency to the list to be installed, and that would show by a recent update of the script `install_dependencies.sh`. So maybe keep an eye for changes on this script on the main page of the github repository to be sure you're in sync. I will make sure to communicate on the thread when it is the case. 
But in most cases, updating the scripts in the git repo is all you need. That's what the alias command `panup` does, when loaded in your environment.
It's more a shortcut than a workaround - as there is nothing to work around.
In the case where you put your copy of the pantagruel repository in the hypothetical folder `~/software/`, `panup` would be defined by the command 
```alias panup='cd ~/software/pantagruel/ && git pull && git submodule update && cd -'```
and calling it would correspond to doing this suite of commands:
```
cd ~/software/pantagruel/
git pull
git submodule update
cd - #means it returns to the folder your were in at the beginning of the call
```
There is one case where it could not be so easy, which is if you don't have network access on your server. In that case, I recommend to do the regular update on your local machine (e.g. your laptop) and to copy the repository folder from there onto your server, using commands `scp -p` or better `rsync -az`, or any other file transfer protocol if you don't have a Unix command line environment on your local machine.

i hope this helps.

Regards,

Florent
