### ISSUE TITLE
Task 5 failed: How to install lsd on server

### ISSUE THREAD

**Issue by megaptera-helvetiae** [flass/pantagruel#32]
Hola Florent!

I tried to install lsd on our server but failed because I cannot use 'sudo' 

It seems I need lsd. I would prefer doing all the steps of the pipeline on our server. Is there a way around it?

https://github.com/Peltoche/lsd

Here is my error:

````
/scratch/clamchatka/Panta/pantagruel/scripts/pipeline/pantagruel_pipeline_05_core_genome_ref_tree.sh: line 429: lsd: command not found
ERROR: failed ultrametrization of reference tree
ERROR: Pantagruel pipeline task 5: failed.
````

**Comment by flass** [comment]
Hi Laetitia,

yes you need LSD installed, but the software you mention above is not at all the one I mean (it is a fairly common acronym). 

LSD, the one developed by O. Gascuel et al. for ultrametrisation of a phylogenetic tree, should already be installed through the execution of Pantagruel's `install_dependencies.sh` script.

If you want to install it manually, you can refer to the content of said script to see what needs to be done:
(assuming that `$SOFTWARE` is where you mean to install you third-parrty software, and `$BINS` is a folder listed in your `$PATH` so that executables in there will be available in the command line).
```sh
cd ${SOFTWARE}/
wget https://github.com/tothuhien/lsd-0.3beta/releases/download/v0.3.3/lsd_unix
chmod +x ${SOFTWARE}/lsd_unix
ln -s ${SOFTWARE}/lsd_unix ${BINS}/lsd
```
