### ISSUE TITLE
task 7 inconstitency

### ISSUE THREAD

**Issue by kuzman1306** [flass/pantagruel#37]
Dear Florent,

I am using Pantagruel pipeline on Ubuntu 18.04 LTS platform. I used install_dependencies.sh script to install dependencies.

I noticed an inconsistency in the execution of the task 7 (please see picture attached). Optimization took a while, and the pipeline continued with other gene families without problem. I am not sure how frequent this "error" happens.

I wonder if you have an idea what could went wrong here.

Cheers,

Nemanja

![IMG_20200509_124430](https://user-images.githubusercontent.com/52930356/81484060-f8ed0080-9242-11ea-80d8-52f5e654eb36.jpg)

**Comment by flass** [comment]
hi Nemanja,

looking closely at the bug, it seems it is innocuous, and that the job should have proceeded correctly in spite of those error messages, because the step that fails is only in the background daemon that checks that the ALE process is not using too much memory.
the bug is due to un-specific matching of process ids that leads to fail making the memory limit check - but that does not prevent ALE to keep running. the bug should only happen in a limited range of cases (small process id numbers) and so it is unlikely to cause an issue, as it is only needed in the rare case when the ALE job would go over the available memory (but in that case it could crash the run or even your server :-/ )
this has been fixed in commit 906f14e, so if you can please make that safety update (I'll push it on the dockerhub too), but really I don't think it is that critical and if you have an older version currently running the pipeline I would not interrupt the run just for that.
