### ISSUE TITLE
Usage: the init command - not working 

### ISSUE THREAD

**Issue by ElitaJaun** [flass/pantagruel#4]
Dear Florent, 

I am not able to run the example of pantagruel usage as given:
pantagruel -d databasename -r /root/folder/for/database -f PANTAGFAM -I email -A /folder/of/public/genome/in/RefSeq/format init

I ran:
```sh
$ pantagruel -d test -r ./ -f PANTAGFAM -I e.jauneikaite@imperial.ac.uk -A GCF_000007265.1_ASM726v1/ init
```
but got the following error:
```
set gene family prefix to 'PANTAGFAM'
set identity to 'e.jauneikaite@imperial.ac.uk'
set NCBI RefSeq(-like) genome assembly source folder to 'GCF_000007265.1_ASM726v1/'
will create/use Pantagruel database 'test', set in root folder: './'

will run tasks: init
[2019-02-22 14:37:09] Pantagrel pipeline step init: initiate pangenome database.
/home/elita/pantagruel_pipeline/pantagruel/scripts/pipeline/pantagruel_pipeline_master.sh: line 472: setdefaults: command not found
/home/elita/pantagruel_pipeline/pantagruel/scripts/pipeline/pantagruel_pipeline_master.sh: line 473: /scripts/pipeline/pantagruel_pipeline_init.sh: No such file or directory
ERROR: 
```

How could I check that I have all the required commands/scripts installed correctly? 

Thank you. 
Bw, 
Elita

**Comment by flass** [comment]
Hi Elita, 
thanks for the bug reports.

- about the bug relative to `setdefaults`; there was a syntax error, fixed in commits 4c90719 and 37bd608.

- the bug relative to not finding the script was due to you not specifying the hard path to the Pantagruel code repository through -p option. This option seemed rather a source of confusion to the program than anything useful, I removed it (commit 478057f) and fixed the automatic detection of the code repository path (commits 478057f and c93ef2e).

- Also I noticed you were using relative paths for various arguments, and made the master script robust to relative path in input arguments (commit 3177cd9).

- In addition, I see you are specifying  a single assembly folder as value for option `-A`. This is not the correct syntax: you have to provide a folder that contains folder(s) of assemblies (cf. description of input  in [README](https://github.com/flass/pantagruel#input-data)). 

- Finally, you need to provide a minimum of 4 genomes, or Pantagruel will return an error in task 00. I clarified these last two point in the README (commit a024d9e).

I tested `init` task with your command and it should work fine (as for commit 66f1f27). Please let me know if anything else goes wrong.

Cheers,
Florent

**Comment by ElitaJaun** [comment]
Hi Florent,
Thank you - it all works now. 
Bw, 
Elita

**Comment by flass** [comment]
Great, thanks for reporting.
